### ISSUE TITLE
eft-generator addDebitTransaction funcion request parametre add

### ISSUE THREAD

**Issue by ovesh786** [cityssm/node-eft-generator#27]
Hello, i want to add request parameter to this function,

```
const eftGenerator = new EFTGenerator({
  originatorId: '0123456789',
  originatorShortName: 'SSM',
  originatorLongName: 'The City of Sault Ste. Marie',
  fileCreationNumber: '0001'
})

eftGenerator.addDebitTransaction({
  bankInstitutionNumber: '111',
  bankTransitNumber: '22222',
  bankAccountNumber: '333333333',
  cpaCode: CPA_CODES.PropertyTaxes,
  amount: 1234.56,
  payeeName: 'Test Property Owner',
  **institutionId:"003000340"**,
  **AccountNo:'101001789261'**
})
```

i want set institutionId for retrun as position 194-202 and AccountNo for return 203-214 so can I use this 2 parameter like that and should I change in 
`export interface EFTTransactionSegment {
  cpaCode: number
  /**
   * In dollars
   */
  amount: number
  /**
   * If not set, will use today.
   */
  paymentDate?: Date
  /**
   * Three digits
   */
  bankInstitutionNumber: string
  /**
   * Five digits
   */
  bankTransitNumber: string
  /**
   * Up to 12 digits
   */
  bankAccountNumber: string
  payeeName: string
  crossReferenceNumber?: string
  institutionId?: string
  AccountsNo?: string
}
`
interface like that?

**Comment by dangowans** [comment]
Thanks for the issue @ovesh786 .

Optional parameters have been added to the main constructor to handle a return account. See the new v0.1.0 release.

```javascript
const eftGenerator = new EFTGenerator({
  originatorId: '0123456789',
  originatorShortName: 'SSM',
  originatorLongName: 'The City of Sault Ste. Marie',
  fileCreationNumber: '0001',

  returnInstitutionNumber: '001',
  returnTransitNumber: '00002',
  returnAccountNumber: '345'
})
```

Hopefully this change will meet your needs.
